name: Build on development

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'

    - name: Set environment
      run: cp ./.env.dev ./.env

    - name: Install Yarn
      run: npm install yarn -g

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
    - name: Deploy to public dirrectory
      run: mkdir -p /var/www/consilium-app && cp -r ./dist/* /var/www/consilium-app/